// examples/shared/src/logic/react/useTheme.ts
/**
 * React hook for theme management
 *
 * Provides theme state and toggle function with automatic DOM updates
 * and localStorage persistence.
 */
import { useEffect, useState } from "react";

import { applyTheme, getInitialTheme, type Theme, toggleTheme } from "../theme";

export function useTheme() {
  const [theme, setTheme] = useState<Theme>(getInitialTheme);

  useEffect(() => {
    applyTheme(theme);
  }, [theme]);

  const toggle = () => {
    setTheme((prev) => toggleTheme(prev));
  };

  return { theme, toggle };
}

// examples/shared/src/logic/solid/useTheme.ts
/**
 * Solid primitive for theme management
 *
 * Provides theme signal and toggle function with automatic DOM updates
 * and localStorage persistence.
 */
import { createEffect, createSignal } from "solid-js";

import { applyTheme, getInitialTheme, type Theme, toggleTheme } from "../theme";

export function useTheme() {
  const [theme, setTheme] = createSignal<Theme>(getInitialTheme());

  createEffect(() => {
    applyTheme(theme());
  });

  const toggle = () => {
    setTheme((prev) => toggleTheme(prev));
  };

  return { theme, toggle };
}
