// examples/shared/src/logic/react/useWorldalityWidget.ts
/**
 * React hook for Worldality widget management
 *
 * Handles widget initialization, theme updates, and cleanup.
 * Returns a ref to attach to the locale button.
 */
import { useEffect, useRef } from "react";

import { WorldalityWidget } from "worldality/widget";

import { type Theme, WORLDALITY_CONFIG } from "../constants";

export function useWorldalityWidget(theme: Theme) {
  const buttonRef = useRef<HTMLButtonElement>(null);
  const widgetRef = useRef<WorldalityWidget | undefined>(undefined);

  useEffect(() => {
    widgetRef.current = new WorldalityWidget({ ...WORLDALITY_CONFIG, theme });

    if (buttonRef.current) {
      const detach = widgetRef.current.attachTo(buttonRef.current);
      return () => {
        detach();
        widgetRef.current?.destroy();
      };
    }
  }, [theme]);

  return { buttonRef };
}

// shared/src/logic/solid/useWorldalityWidget.ts
/**
 * Solid primitive for Worldality widget management
 *
 * Handles widget initialization, theme updates, and cleanup.
 * Returns a setter for the button ref.
 */
import { type Accessor, createEffect, onCleanup, onMount } from "solid-js";
import { WorldalityWidget } from "worldality/widget";

import { type Theme, WORLDALITY_CONFIG } from "../constants";

export function useWorldalityWidget(theme: Accessor<Theme>) {
  let buttonRef: HTMLButtonElement | undefined;
  let widget: WorldalityWidget | undefined;
  let detach: (() => void) | undefined;

  onMount(() => {
    widget = new WorldalityWidget({ ...WORLDALITY_CONFIG, theme: theme() });

    if (buttonRef) {
      detach = widget.attachTo(buttonRef);
    }

    onCleanup(() => {
      detach?.();
      widget?.destroy();
    });
  });

  // Update widget when theme changes
  createEffect(() => {
    if (widget) {
      widget.destroy();
      widget = new WorldalityWidget({ ...WORLDALITY_CONFIG, theme: theme() });
      if (buttonRef) {
        detach = widget.attachTo(buttonRef);
      }
    }
  });

  return {
    setButtonRef: (el: HTMLButtonElement) => {
      buttonRef = el;
    },
  };
}
