// examples/react/src/App.tsx
import { useCurrentPage, useLocaleRouting } from "worldality/react";

import { AboutPage } from "./pages/about";
import { IndexPage } from "./pages/index";

export default function App() {
  const currentPage = useCurrentPage();

  useLocaleRouting();

  return currentPage === "about" ? <AboutPage /> : <IndexPage />;
}

// vue/src/App.vue
<script setup lang="ts">
import { useCurrentPage, useLocaleRouting } from "worldality/vue";

import AboutPage from "./pages/about.vue";
import IndexPage from "./pages/index.vue";

const currentPage = useCurrentPage();

useLocaleRouting();
</script>

<template>
  <AboutPage v-if="currentPage === 'about'" />
  <IndexPage v-else />
</template>
