// examples/vue/src/components/Layout.vue
<script setup lang="ts">
import { useCurrentLocale } from "worldality/vue";

import Controls from "./Controls.vue";
import Header from "./Header.vue";

const locale = useCurrentLocale();
</script>

<template>
  <div
    :dir="locale.direction"
    class="flex min-h-screen items-start bg-background font-sans antialiased"
  >
    <div class="mx-auto w-full max-w-4xl px-4 py-16">
      <Header />
      <main class="space-y-8">
        <Controls />
        <slot />
      </main>
    </div>
  </div>
</template>

// react/src/components/Layout.tsx
import { type ReactNode } from "react";

import { useCurrentLocale } from "worldality/react";

import { Controls } from "./Controls";
import { Header } from "./Header";

type LayoutProps = {
  children: ReactNode;
};

export function Layout({ children }: LayoutProps) {
  const locale = useCurrentLocale();

  return (
    <div
      dir={locale.direction}
      className="flex min-h-screen items-start bg-background font-sans antialiased"
    >
      <div className="mx-auto w-full max-w-4xl px-4 py-16">
        <Header />
        <main className="space-y-8">
          <Controls />
          {children}
        </main>
      </div>
    </div>
  );
}
