// examples/react/src/App.tsx
import { useCurrentPage, useLocaleRouting } from "worldality/react";

import { AboutPage } from "./pages/about";
import { IndexPage } from "./pages/index";

export default function App() {
  const currentPage = useCurrentPage();

  useLocaleRouting();

  return currentPage === "about" ? <AboutPage /> : <IndexPage />;
}

// solid/src/App.tsx
import { Match, Switch } from "solid-js";
import { useCurrentPage, useLocaleRouting } from "worldality/solid";

import { AboutPage } from "./pages/about";
import { IndexPage } from "./pages/index";

export default function App() {
  const currentPage = useCurrentPage();

  useLocaleRouting();

  return (
    <Switch fallback={<IndexPage />}>
      <Match when={currentPage() === "about"}>
        <AboutPage />
      </Match>
    </Switch>
  );
}
